url:                    http://localhost/kostyanetsky.ru
language_code:          ru
mirror_url:             http://localhost/kostyanetsky.me
mirror_language_code:   en
github_repository:      vkostyanetsky/kostyanetsky.ru