url:                    http://localhost:8000
language_code:          ru
mirror_url:             https://kostyanetsky.me
mirror_language_code:   en
github_repository:      vkostyanetsky/kostyanetsky.ru