1c:           "1С"
work:         "работа"
english:      "английский"
meanwhile:    "тем временем"
sport:        "спорт"
books:        "книги"
videogames:   "видеоигры"
mssql:        "MS SQL"
films:        "фильмы"
webdev:       "вебдев"
bash:         "bash"
family:       "семья"
optimization: "оптимизация"
workplace:    "рабочее место"
code-smell:   "код с запашком"
powershell:   "PowerShell"
done:         "готово"
pgsql:        "PostgreSQL"
python:       "Python"
blog:         "блог"
nodejs:       "Node.js"
bitrix:       "Битрикс"
swagger:      "Swagger"
typescript:   "TypeScript"
obsidian:     "Obsidian"
georgia:      "Грузия"