1c:           "1С"
work:         "Работа"
english:      "English"
meanwhile:    "Тем временем"
sport:        "Спорт"
books:        "Книги"
videogames:   "Видеоигры"
mssql:        "MS SQL"
films:        "Фильмы"
webdev:       "Вебдев"
bash:         "Bash"
family:       "Семья"
optimization: "Оптимизация"
workplace:    "Рабочее место"
code-smell:   "Код с запашком"
powershell:   "PowerShell"
done:         "Готово"
pgsql:        "PostgreSQL"
python:       "Python"
blog:         "Блог"
nodejs:       "Node.js"
bitrix:       "Битрикс"
swagger:      "Swagger"
javascript:   "JavaScript"
typescript:   "TypeScript"
obsidian:     "Obsidian"
georgia:      "Грузия"
ai:           "ИИ"
3d:           "3D"
