name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Tell something
        run: curl 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?text=111&chat_id=${{ secrets.TELEGRAM_CHAT_ID }}'

      - name: Tell something
        run: |
