name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Clone BlogBuilder repository
        run: |
          mkdir BlogBuilder
          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/vkostyanetsky/BlogBuilder.git" --branch main --single-branch ./BlogBuilder
        working-directory: /home/runner/work
                
      - name: Clone kostyanetsky.ru repository
        run: |
          mkdir output
          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/vkostyanetsky/kostyanetsky.ru.git" --branch master --single-branch ./kostyanetsky.ru
        working-directory: /home/runner/work
    
      - name: Where
        run: ls
