name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Clone BlogBuilder repository
        run: |
          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/vkostyanetsky/BlogBuilder.git" --branch main --single-branch builder
                
      - name: Clone kostyanetsky.ru repository
        run: |
          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/vkostyanetsky/kostyanetsky.ru.git" --branch master --single-branch output

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Build blog
        run: python builder/builder.py --input . --output output --config config.yaml
