name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: pwd
        run: pwd

      - name: ls1
        run: ls

      - name: ls2
        run: ls
        working-directory: /home/runner/work/

      - name: ls3
        run: ls
        working-directory: /home/runner/work/data.kostyanetsky.ru/
